### ISSUE TITLE
Cluster management API

### ISSUE THREAD

**Issue by leoluk** [monogon-dev/monogon#30] opened 2021-07-05 14:45 UTC
(originally reported by @q3k in T491)

Implement the API part of the cluster lifecycle design doc:

- day-to-day management operations of the cluster (status, node add/remove, node trust/untrust, etc)
- escrow into k8s credentials

**Comment by q3k** [comment] 2021-07-06 12:46
Duplicate of monogon-dev/monogon#24.

**Closed by q3k** 2021-07-06 12:46 UTC
Labels: c/cluster, enhancement
